language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - ~/.npm
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
before_install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
after_install:
  - npm run travis-deploy-once "npm run semantic-release"
install:
  - npm install
script:
  - npm run test:prod && npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
