language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - ~/.npm
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
install:
  - npm install
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
